language: python
python:
  - "2.7"
  - "3.2"

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - python: "2.7"

script:
  - nosetests tests --with-coverage --cover-package=nlglib --cover-erase --cover-html --rednose
